/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkSegmentationFilter.h

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
// .NAME vtkSegmentationFilter - generate scalars along a specified direction
// .SECTION Description
// vtkSegmentationFilter is a filter to generate scalar values from a
// dataset.  The scalar values lie within a user specified range, and
// are generated by computing a projection of each dataset point onto
// a line. The line can be oriented arbitrarily. A typical example is
// to generate scalars based on elevation or height above a plane.

#ifndef __vtkSegmentationFilter_h
#define __vtkSegmentationFilter_h

#include "vtkExtractVOI.h"

class VTK_EXPORT vtkSegmentationFilter : public vtkExtractVOI
{
public:
  static vtkSegmentationFilter* New();
  vtkTypeMacro(vtkSegmentationFilter, vtkExtractVOI);
  void PrintSelf(ostream& os, vtkIndent indent);

protected:
  vtkSegmentationFilter();
  ~vtkSegmentationFilter();

private:
  vtkSegmentationFilter(const vtkSegmentationFilter&);  // Not implemented.
  void operator=(const vtkSegmentationFilter&);  // Not implemented.
};

#endif
